#!/bin/bash
if [[ $1 == "--build" ]]; then
  opts=$1
  source_file=$2
  ./GLA $1 && ./GSA $1
elif [[ $1 == "--build-only" ]]; then
  ./GLA --build && ./GSA --build && ./LA $1 && ./SA $1 && ./GEN $1
  exit
else
  source_file=$1
fi

if [[ ! -f $source_file ]]; then
  echo "File not found: $source_file" >&2
  exit
fi

./LA $opts < $source_file | ./SA $opts | ./GEN $opts
